name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Composer Dependencies
      run: composer install --no-interaction --no-progress --no-suggest

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy to cPanel
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 1978 
        script: |
          cd /home/relymasolutions/pos
          git pull origin main
   
